"""initial schema

Revision ID: 9ed2a3403e81
Revises: 
Create Date: 2026-05-13 10:32:05.673489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ed2a3403e81'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('maintenance_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_pruned_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracked_apps',
    sa.Column('app_id', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('internal_category', sa.String(length=100), nullable=False),
    sa.Column('ios_app_id', sa.String(length=200), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('app_id')
    )
    op.create_index(op.f('ix_tracked_apps_internal_category'), 'tracked_apps', ['internal_category'], unique=False)
    op.create_table('opportunity_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('problem_statement', sa.Text(), nullable=False),
    sa.Column('audience', sa.String(length=300), nullable=True),
    sa.Column('why_now', sa.Text(), nullable=True),
    sa.Column('specificity', sa.Integer(), nullable=False),
    sa.Column('lifecycle_state', sa.String(length=50), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('labeller_model', sa.String(length=100), nullable=True),
    sa.Column('centroid', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('embedding_model', sa.String(length=150), nullable=True),
    sa.Column('merged_into_id', sa.Integer(), nullable=True),
    sa.Column('last_evidence_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_labelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['merged_into_id'], ['opportunity_candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_candidates_category_id'), 'opportunity_candidates', ['category_id'], unique=False)
    op.create_index(op.f('ix_opportunity_candidates_embedding_model'), 'opportunity_candidates', ['embedding_model'], unique=False)
    op.create_index(op.f('ix_opportunity_candidates_is_archived'), 'opportunity_candidates', ['is_archived'], unique=False)
    op.create_index(op.f('ix_opportunity_candidates_labeller_model'), 'opportunity_candidates', ['labeller_model'], unique=False)
    op.create_index(op.f('ix_opportunity_candidates_lifecycle_state'), 'opportunity_candidates', ['lifecycle_state'], unique=False)
    op.create_table('source_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('extraction_state', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'external_id', name='uq_source_items_source_external')
    )
    op.create_index(op.f('ix_source_items_category_id'), 'source_items', ['category_id'], unique=False)
    op.create_index(op.f('ix_source_items_extraction_state'), 'source_items', ['extraction_state'], unique=False)
    op.create_index(op.f('ix_source_items_role'), 'source_items', ['role'], unique=False)
    op.create_index(op.f('ix_source_items_source_type'), 'source_items', ['source_type'], unique=False)
    op.create_table('candidate_briefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('headline', sa.String(length=500), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('evidence_json', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['opportunity_candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_briefs_candidate_id'), 'candidate_briefs', ['candidate_id'], unique=False)
    op.create_table('candidate_score_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('score_total', sa.Float(), nullable=False),
    sa.Column('score_breakdown_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['opportunity_candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_score_history_candidate_id'), 'candidate_score_history', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_score_history_scored_at'), 'candidate_score_history', ['scored_at'], unique=False)
    op.create_table('candidate_validations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('source_item_id', sa.Integer(), nullable=True),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('signal_value', sa.Float(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['opportunity_candidates.id'], ),
    sa.ForeignKeyConstraint(['source_item_id'], ['source_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_validations_candidate_id'), 'candidate_validations', ['candidate_id'], unique=False)
    op.create_table('lifecycle_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('old_state', sa.String(length=50), nullable=True),
    sa.Column('new_state', sa.String(length=50), nullable=True),
    sa.Column('score_total', sa.Float(), nullable=True),
    sa.Column('was_alerted', sa.Boolean(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['opportunity_candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lifecycle_events_candidate_id'), 'lifecycle_events', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_lifecycle_events_recorded_at'), 'lifecycle_events', ['recorded_at'], unique=False)
    op.create_table('pain_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_item_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('extractor_model', sa.String(length=100), nullable=False),
    sa.Column('problem_text', sa.Text(), nullable=True),
    sa.Column('audience', sa.String(length=300), nullable=True),
    sa.Column('urgency_cue', sa.String(length=200), nullable=True),
    sa.Column('current_workaround', sa.Text(), nullable=True),
    sa.Column('embedding', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('embedding_model', sa.String(length=150), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['opportunity_candidates.id'], ),
    sa.ForeignKeyConstraint(['source_item_id'], ['source_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pain_points_candidate_id'), 'pain_points', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_pain_points_embedding_model'), 'pain_points', ['embedding_model'], unique=False)
    op.create_index(op.f('ix_pain_points_extracted_at'), 'pain_points', ['extracted_at'], unique=False)
    op.create_index(op.f('ix_pain_points_source_item_id'), 'pain_points', ['source_item_id'], unique=False)
    op.create_table('candidate_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('brief_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=10), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brief_id'], ['candidate_briefs.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['opportunity_candidates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'user_id', 'brief_id', name='uq_candidate_feedback')
    )
    op.create_index(op.f('ix_candidate_feedback_candidate_id'), 'candidate_feedback', ['candidate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_feedback_candidate_id'), table_name='candidate_feedback')
    op.drop_table('candidate_feedback')
    op.drop_index(op.f('ix_pain_points_source_item_id'), table_name='pain_points')
    op.drop_index(op.f('ix_pain_points_extracted_at'), table_name='pain_points')
    op.drop_index(op.f('ix_pain_points_embedding_model'), table_name='pain_points')
    op.drop_index(op.f('ix_pain_points_candidate_id'), table_name='pain_points')
    op.drop_table('pain_points')
    op.drop_index(op.f('ix_lifecycle_events_recorded_at'), table_name='lifecycle_events')
    op.drop_index(op.f('ix_lifecycle_events_candidate_id'), table_name='lifecycle_events')
    op.drop_table('lifecycle_events')
    op.drop_index(op.f('ix_candidate_validations_candidate_id'), table_name='candidate_validations')
    op.drop_table('candidate_validations')
    op.drop_index(op.f('ix_candidate_score_history_scored_at'), table_name='candidate_score_history')
    op.drop_index(op.f('ix_candidate_score_history_candidate_id'), table_name='candidate_score_history')
    op.drop_table('candidate_score_history')
    op.drop_index(op.f('ix_candidate_briefs_candidate_id'), table_name='candidate_briefs')
    op.drop_table('candidate_briefs')
    op.drop_index(op.f('ix_source_items_source_type'), table_name='source_items')
    op.drop_index(op.f('ix_source_items_role'), table_name='source_items')
    op.drop_index(op.f('ix_source_items_extraction_state'), table_name='source_items')
    op.drop_index(op.f('ix_source_items_category_id'), table_name='source_items')
    op.drop_table('source_items')
    op.drop_index(op.f('ix_opportunity_candidates_lifecycle_state'), table_name='opportunity_candidates')
    op.drop_index(op.f('ix_opportunity_candidates_labeller_model'), table_name='opportunity_candidates')
    op.drop_index(op.f('ix_opportunity_candidates_is_archived'), table_name='opportunity_candidates')
    op.drop_index(op.f('ix_opportunity_candidates_embedding_model'), table_name='opportunity_candidates')
    op.drop_index(op.f('ix_opportunity_candidates_category_id'), table_name='opportunity_candidates')
    op.drop_table('opportunity_candidates')
    op.drop_index(op.f('ix_tracked_apps_internal_category'), table_name='tracked_apps')
    op.drop_table('tracked_apps')
    op.drop_table('maintenance_state')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
